In [ ]:
#single dimensional array

In [4]:
import numpy as np

In [5]:

n=np.array([10,20,30,40,50])
n

array([10, 20, 30, 40, 50])

In [6]:
#multi dimensional array

In [10]:

n1=np.array([[10,20,30,40],[50,60,70,80]])
n1

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [11]:
type(n)

numpy.ndarray

In [12]:
n0=np.zeros((2,2))
n0

array([[0., 0.],
       [0., 0.]])

In [13]:
type(n0)

numpy.ndarray

In [14]:
ns=np.full((2,2),10)
ns

array([[10, 10],
       [10, 10]])

In [16]:
nar=np.arange(10,20)
nar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
naa=np.arange(10,50,5)
naa

array([10, 15, 20, 25, 30, 35, 40, 45])

In [19]:
nr=np.random.randint(1,100,5)
nr

array([45,  1, 97, 61,  3])

In [25]:
nsh=np.array([[1,2,3],[4,5,6]])
nsh.shape

(2, 3)

In [26]:
nsh

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
nsh.shape=(3,2)
nsh.shape

(3, 2)

In [28]:
nsh

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [30]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [33]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
c=np.array([1,2,3,4,5,6])
d=np.array([5,6,7,8,9])

In [40]:
np.intersect1d(c,d)

array([5, 6])

In [41]:
np.setdiff1d(c,d)

array([1, 2, 3, 4])

In [42]:
np.setdiff1d(d,c)

array([7, 8, 9])

In [45]:
s=np.array([10,20])
t=np.array([30,40])

In [46]:
np.sum([s,t])

100

In [47]:
np.sum([s,t],axis=0)

array([40, 60])

In [48]:
np.sum([s,t],axis=1)

array([30, 70])

In [49]:
m=np.array([10,20,30])

In [51]:
m=m+1
m

array([11, 21, 31])

In [52]:
m=m-1
m

array([10, 20, 30])

In [53]:
m=m*2
m

array([20, 40, 60])

In [54]:
m=m/2
m

array([10., 20., 30.])

In [55]:
k=np.array([10,20,30,40,50,60])

In [57]:
np.mean(k)

35.0

In [58]:
np.median(k)

35.0

In [59]:
np.std(k)

17.07825127659933

In [60]:
np.save('my numpy',k)#saving

In [61]:
l=np.load('my numpy.npy')#loading
l

array([10, 20, 30, 40, 50, 60])